server:
  port: 10319

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nhnacademy-be10-1lluwa/config-repo.git
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: DEBUG
