server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nhnacademy-be10-1lluwa/bookstore-infra.git
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: health, refresh

  endpoint:
    health:
      show-details: always